name: Convert Resume to PDF and HTML

on:
  push:
    branches-ignore:
      - main # Trigger on all branch pushes except main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Create output directory and use pandoc
        run: |
          mkdir output
          cp style.css output/
          cp -r assets output/

      - name: pandoc generate html
        uses: docker://pandoc/latex
        with:
          args: >-
            --standalone
            --output=output/resume.html
            --css=style.css
            resume.md

      - name: generate pdf
        run: wkhtmltopdf --enable-local-file-access --page-height 100m output/resume.html output/resume.pdf

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: resume.pdf
          path: output/resume.pdf
